# Generated by Django 4.2.2 on 2023-07-23 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=50)),
                ('task_title', models.CharField(max_length=50)),
                ('complete_by', models.DateTimeField()),
                ('task_detail', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=50)),
                ('completed_on', models.DateTimeField(default=None)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Personal', 'Personal'), ('Loan', 'Loan'), ('Food', 'Food'), ('Shopping', 'Shopping')], default='Personal', max_length=50)),
                ('payment_date', models.DateTimeField()),
                ('amount', models.FloatField(default=0.0)),
                ('payment_for', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('payment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0.0)),
                ('started_on', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='EMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('note', models.CharField(default=None, max_length=100)),
                ('paid_on', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.loan')),
            ],
        ),
    ]
