# Generated by Django 4.2.7 on 2025-01-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='reminder_time',
            new_name='reminder_date',
        ),
    ]
